### ISSUE TITLE
archiveTARFiles

### ISSUE THREAD

**Issue by getvictor** [kpelykh/docker-java#2]
I'm seeing a couple issues in archiveTARFiles.

Deleting the tarFile on exit seems like a bad approach for long running applications. I recommend deleting the tarFile immediately after the new image is built. `tarFile.deleteOnExit();`

I need to add an executable file to the new image with the following line in Dockerfile:
`ADD run.sh /`
When using DockerClient.build method, the file becomes non-executable in the image. Using the command-line `docker build .` adds the file correctly with permissions intact.

**Comment by kpelykh** [comment]
Unfortunately Java doesn't allow copying of metadata along with file, therefore all information about file's permissions is dropped. This is well know issue and has been fixed in Java 7. 

Workaround would be to explicitly chmod executable file in Dockerfile, e.g.

add ./testrun.sh       /tmp/
run cp /tmp/testrun.sh /usr/local/bin/ && chmod +x /usr/local/bin/testrun.sh

**Comment by getvictor** [comment]
@kpelykh I was using Java 7 when I ran into the metadata issue originally. Do I still need the workaround when running Java 7 after your recent check-in? If so, perhaps you could tell me the local change I need to make to get the copying working with Java 7?

**Comment by kpelykh** [comment]
@getvictor docker-java is using Java 6 API, so compiling with Java 7 will not solve the problem. I'll create java-7 branch and will change code to use Java 7 API.

**Comment by getvictor** [comment]
@kpelykh That would be great. Now that Java 6 is end-of-life, most new projects should be using Java 7.

**Comment by kpelykh** [comment]
Added support for java 7 and fixed the issue with permissions. Please check out java-7 branch

**Comment by getvictor** [comment]
Thank you. I'll try it out.
